version: "3.9"
services:
  sandbox:
    image: cadic/oss_api
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: oss_api
    volumes:
      - $PWD/docker/static/entrypoint:/entrypoint
      - $HOME/.ssh:/home/foo/.ssh
      - ./:/workspace
    tty: true
    restart: always
    environment:
      - PYTHONPATH=/workspace
      - PUID=1000
      - PGID=1000
      - ENTRYPOINT=http://0.0.0.0:8080
    entrypoint: /entrypoint
    user: foo
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
